### ISSUE TITLE
Change the columns class 

### ISSUE THREAD

**Issue by moshfeu** [kristoferjoseph/flexboxgrid#148]
**The problem**

I want to use `flexboxgrid` **and** `bootstrap grid system` in the same page.

**The solution**

Add `flexboxgrid` version with different clasess. For example: instead of `col-md-4` it will be `f-col-md-4`

**Comment by BogdanRobertA** [comment]
I do that for you.
I change `.container` with `.f-container`
`.container-fluid` with `.f-container-fluid`
`.row` with `.f-row`
`.col-` with `.f-col-`

Pastebin link : http://pastebin.com/hwTAJkxF

**Comment by kristoferjoseph** [comment]
I *HIGHLY* recommend only using *one* grid system in your project. I won't be changing fbg to make this possible because I feel it is a bad idea. You can make a build without the bootstrap grid and the classes in flexboxgrid were changed to make it a drop in replacement. 
Would really like to hear if people are able to do that though, because I am not a fan of the boostrap class names and would much rather switch them back to how I originally intended them.
