### ISSUE TITLE
Doesn't .container need padding left and right?

### ISSUE THREAD

**Issue by Stegosource** [kristoferjoseph/flexboxgrid#174]
I just added this framework to a new project in place of Bootstrap and am very excited to get started with it, but I did notice a little issue. The .container in Bootstrap has padding left and right 15px, but in Flexboxgrid is has no padding. This creates a problem when you insert a .row element because the .row has negative left and right margins.

**Comment by dappiu** [comment]
I am facing the same issue, I suppose. I'm new to HTML/CSS development, but I don't think I should get an horizontal scrollbar with the example code I put on this [jsbin](http://jsbin.com/kovejobaqo). The problem for me seems to be the `row` class which includes

```css
margin-right: -.5rem;
margin-left: -.5rem;
```

**Comment by AustinGil** [comment]
Haha. Yeah, I see your issue.

Well, I think there are two things here...

1) I found this project when I was looking for a flexbox grid, and I really
was looking forward to using it because it was, from what I gathered, based
on Bootstrap. I guess it was only inspired by BS and I just jumped to
conclusions. I think getting it closer to BS compatibility would be a great
move if you are getting a lot of interest from the BS users because it
would be a HUGE market, but that would also mean that you would need to get
it closer to how BS works. Otherwise, you get people that are expecting one
thing and get something else.

2) If you want to do your own thing, I think you should. If you try to make
too many people happy, you will not be happy yourself, and probably wont be
able to please everyone, so if the .container was not part of the original
plans, and you dont like it, take it out. BS 4 is coming out soon and will
include support for a flexbox grid, so you can always point people in that
direction. If you go this route, I would just recommend not mentioning BS
so that you dont get as much confusion.


Keep in mind, Im not trying to direct you in any way, but since you asked
for input, this is what I got. I think it's a cool project.


To Infinity and Beyond,
*Austin Gil*

**Comment by kristoferjoseph** [comment]
Great feedback! Thanks for thinking this through :)
Does reading this thread #170 sway you one way or another?

**Comment by AustinGil** [comment]
Well, honestly I think BS is a bit bloated. So I ONLY include the grid for
my purposes (15kb unzipped).

So I was originally looking for a replacement, not a drop-in solution. I
liked the fact that it was said to work like BS because my team is used to
that. The only problem I saw was with the container stretching full with. I
like how BS keeps a 15px padding.

I think my advice for you would be to drop the connection with BS. They are
going to have their own flexbox grid in BS4 and people that are tied to BS
will go that way anyway.

You have the opportunity to create your own standalone framework and do
things just the way you see fit.

It sucks it wont be quite what I PERSONALLY was looking for, but if I was
in your position, thats what I would do.


To Infinity and Beyond,
*Austin Gil*

On Wed, May 11, 2016 at 11:36 AM, Kristofer Joseph <notifications@github.com

**Comment by kristoferjoseph** [comment]
Thank you very much for the feedback I really appreciate the thoughts. ✨ 💖 ✨
