### ISSUE TITLE
fallback

### ISSUE THREAD

**Issue by z1haze** [kristoferjoseph/flexboxgrid#176]
Do you have anything so this will work without flex support? like a fallback to table or something

**Comment by hotforfeature** [comment]
What about adding support for the [flexibility polyfill](https://github.com/10up/flexibility)?

All that would be required would be adding `-js-display: flex` anywhere `display: flex` is. I could put together a quick pull request if that'd be a desired feature.

**Comment by kristoferjoseph** [comment]
I had made this a while back as a POC:
https://github.com/kristoferjoseph/flextable 

thoughts?

**Comment by hotforfeature** [comment]
The issue with a `display: table` fallback is that you could almost double the size of the stylesheet adding extra rules. You could have a separate stylesheet that is dynamically loaded if no flexbox support is detected, but that could become a bit hacky.

I think the bigger problem is supporting the variations of display style that could arise when supporting both flexbox and table displays. One thing may work well in flexbox but look different in tables, causing quite the effort for required IE use cases. That's where a polyfill may be a better option, since it will be reproducing the flexbox functionality.

**Comment by z1haze** [comment]
Hopefully all the clients will stop complaining about wanting support for ie9 and we'd all be good

**Comment by hotforfeature** [comment]
The current solution I'm using (having to deal with IE client support), is using [postcss-flexibility](https://github.com/7rulnik/postcss-flexibility) to add the `-js-display: flex` to this library and all my other CSS.

Maybe a better solution would be to include information about flexibility and postcss in the README to help other devs integrate them in their build solutions to support IE. The IE use cases will become fewer and fewer since Microsoft has dropped support, so adding special support to this repo might not be the best ideology.

**Comment by Karklis** [comment]
yes, drop old IE, send old IE to hell... Do not support this shit in this repo.

**Comment by kristoferjoseph** [comment]
@hotforfeature will add some notes to the README about fallback options.
