### ISSUE TITLE
FlexboxGrid without Gaps

### ISSUE THREAD

**Issue by sir-script** [kristoferjoseph/flexboxgrid#198]
A FlexboxGrid with customized gap classes (gaps-large, gaps-small... no-gaps) would be nice ;).

But, anyway, thanks for this cool grid system.

**Comment by kristoferjoseph** [comment]
New version will have gutters or no gutters. You will not be able to configure the gutter width, but it will instead be responsive.

**Comment by PolGuixe** [comment]
@kristoferjoseph when you think the new version will be avaialable?

**Comment by kristoferjoseph** [comment]
You can follow along here: https://github.com/kristoferjoseph/flexboxgrid/tree/7.0?files=1

**Comment by PolGuixe** [comment]
I am trying it. For the gutter do I need to add the class to the row?

**Comment by kristoferjoseph** [comment]
@PolGuixe I appreciate your interest, I do! 
You are welcome to play with it while I am developing it. I will be adding documentation soon. Since it isn't released yet expect it to change. Meaning anything I say here will be wrong tomorrow, so going to have to wait till the official release before I say anything official.
With that said, you can check out [flextable](https://github.com/kristoferjoseph/flextable), which works very similarly. ;)

**Comment by dperrymorrow** [comment]
Adding no gaps is as easy as

```css
.row.no-gap {
  margin: 0;
}

.row.no-gap div[class^="col-"] {
  padding: 0;
}
```

I usually add this to each project I use flexboxgrid in, if there is interest I would gladly submit a pull.
