### ISSUE TITLE
Why @media only screen?

### ISSUE THREAD

**Issue by littleguga** [kristoferjoseph/flexboxgrid#200]
Why we need 'only screen'?

**Comment by kristoferjoseph** [comment]
http://stackoverflow.com/questions/8549529/what-is-the-difference-between-screen-and-only-screen-in-media-queries

**Comment by ryanve** [comment]
Is this about why `only` is needed or why `screen` is? The `only` usage in that link seems only relevant for `<link rel="stylesheet">` based on the [origin of the quote in example 9](https://www.w3.org/TR/css3-mediaqueries/#media0). I think it would be better to totally remove `only screen` from the default so that the grid can work in `projection` media too. In other words have the media queries be like

```css
@custom-media --sm-viewport (min-width: 48em);
@custom-media --md-viewport (min-width: 64em);
@custom-media --lg-viewport (min-width: 75em);
```

**Comment by kristoferjoseph** [comment]
interesting @ryanve,
Have you run into this issue of the grid not working in `projection` media?

**Comment by ryanve** [comment]
I have run into the issue with media queries in general before. For example [Opera fullscreen mode is `projection`](http://help.opera.com/Linux/9.22/en/display.html)
