### ISSUE TITLE
Why /css/flexboxgrid.css exist, when we can use /dist/flexboxgrid.css ?

### ISSUE THREAD

**Issue by littleguga** [kristoferjoseph/flexboxgrid#205]
Also in `/css/flexboxgrid.css` 62em is using, when in `/dist/flexboxgrid.css` 64em is using.

**Comment by kristoferjoseph** [comment]
Very interesting. This is a merge issue. There should be only onIy one. Must have come from a PR merge 😦 .

 I am currently updating the build to not have dist or css but instead to have a flat directory and output only flexboxgrid.css and flexboxgrid.min.css.

**Comment by littleguga** [comment]
@kristoferjoseph so, what will be better: wait for the next version or submit a PR?

**Comment by kristoferjoseph** [comment]
I would merge a PR for it, but just know it will be going away [soon](https://m.popkey.co/478df0/47moZ_s-200x150.gif)

**Comment by kristoferjoseph** [comment]
OK I looked into this more and realized this was due to a user being confused by having the styles for the website in the same directory as the distributed css.

Meaning /dist used to have flexboxgrid css as well as flexboxgrid.com css and people got confused.

SO now flexboxgrid css is in dist and flexboxgrid.com css is in css.

Next release the website ONLY live in the gh-pages branch so people are not confused.
