### ISSUE TITLE
Improve code quality and maintainability

### ISSUE THREAD

**Issue by kdex** [kristoferjoseph/flexboxgrid#208]
Recently, #197 was added to expand the decimals for all periodic percentage values. Looking at the code, this feels like a hack; usually, a preprocessor whould be doing this precision work for you, so typing these numbers out by hand every time and counting their decimals clearly lowers maintainability.

There's a few ways how to make flexboxgrid a little more maintainable that come to mind:

1.  Use CSS's `calc` property (e.g. something akin to `calc(100% / 12)` instead of `8.333333333%`). All modern browsers support `calc` (which is be a feasible compromise, since `flex` is only available in modern browsers to begin with, so it doesn't come at a high cost). I've observed that flexboxgrid even uses `calc` internally; is there a reason why not to use it to represent periodic numbers?
2. Use any modern CSS compiler pipeline (PostCSS being the current big thing) and manually compile all `calc()` calls to static values: Essentially, this compiles calc to a precision level that you set at compile-time, see e.g. [postcss-calc](https://github.com/postcss/postcss-calc). It's probably a good idea to use a preprocessor anyway, so that
   - rules that are based on mathematics (like all percentages in `.col-sm-*`) can be generated with a loop instead of using a calculator and typing out the results manually
   - the code can be split up into a modular structure instead of maintaining one big 1000-line file
   - the community can help working on this more; currently, a PR still requires us to view this gigantic CSS file.

Any thoughts?

**Comment by kristoferjoseph** [comment]
Good points. Check out the 7.0 branch.

I used calc before and switched away from it because there were many incompatibility issue between browsers. Seems like they have all coalesced for the most part so am giving it another go.
 
As for preprocessors I am going to be shipping only css and supplying a grid creation tool. There are many forks that offer a pre-precessor du jour offering to complicate your build script with.

Thanks for the feedback!
