### ISSUE TITLE
.row triggers scrollbars on body element

### ISSUE THREAD

**Issue by personable** [kristoferjoseph/flexboxgrid#51]
http://codepen.io/personable/pen/zxNqzQ

Absolutely love this grid -- great work @kristoferjoseph ! I'm just wondering if there's a workaround to this issue I keep bumping up against: If the .row element (or its parent[s]) is flush with the body element, the negative margins cause the body element to throw scrollbars.

Beyond setting overflow-x: hidden on the body or the .row's container, can this be avoided?

**Comment by kristoferjoseph** [comment]
@personable Thanks, I am glad you find it useful.
I've been really wanting to remove the negative margins for some time now. 
They are only really needed when you let your rows wrap.

## Example:
The two screen grabs are of the same amount of rows and the same number of boxes, but because of the magic `flex-wrap` property you can let them wrap to push down the other content.

![screenshot 2015-01-07 16 18 13](https://cloud.githubusercontent.com/assets/76308/5655856/d6dc98fe-9688-11e4-9a29-a4194c8a817a.png)
![screenshot 2015-01-07 16 18 04](https://cloud.githubusercontent.com/assets/76308/5655858/d8fff720-9688-11e4-85f6-413d9f3aa980.png)

This 'feature' is why I added the negative margins.

I could either add a new class to the container to remove this feature, or you can remove the negative margins from the rows yourself for your own site.

The negative margins for rows are here:
https://github.com/kristoferjoseph/flexboxgrid/blob/master/dist/flexboxgrid.css#L46
https://github.com/kristoferjoseph/flexboxgrid/blob/master/dist/flexboxgrid.css#L47

I would just remove them, but this would break backwards compatibility and I personally use this feature a bunch.

Thoughts?

**Comment by kristoferjoseph** [comment]
Thanks! Very happy you find it useful.

Here are some work arounds:
http://codepen.io/dam/pen/EaZymg
http://codepen.io/dam/pen/rajLmx

I've been thinking of ways to remove these. They are used to compensate for the gutters. The issue is compounded when you allow rows to wrap like the example on the home page.

![screenshot 2015-01-07 16 18 04](https://cloud.githubusercontent.com/assets/76308/5656175/6bd9aa4c-968d-11e4-9545-bff063cc27d5.png)
![screenshot 2015-01-07 16 18 13](https://cloud.githubusercontent.com/assets/76308/5656178/6dc73220-968d-11e4-8e70-ae9c04c9b830.png)

Will keep thinking on it.

**Comment by personable** [comment]
Appreciate you taking a look at this so quickly. I'd hate to ask you to remove a grid feature you find useful. I think in our case, the best thing to do will be to create a special class specifying no margin on .row elements that are flush with the body. Problem solved, and no need to mess around with disabling scroll. Thanks so much!

**Comment by Aybee** [comment]
Related https://github.com/kristoferjoseph/flexboxgrid/issues/78#issuecomment-113203555

**Comment by gevgeny** [comment]
@kristoferjoseph Seems codepens with workarounds do not work anymore, could you update them plz ?

**Comment by ghodss** [comment]
@kristoferjoseph As @gevgeny mentioned, the codepen links do not work anymore. Can you paste the workarounds directly into this issue? Thank you!

**Comment by personable** [comment]
Here is a new one: http://codepen.io/personable/pen/revbOq?editors=1100

It simply removes the negative margin on the row that is there to compensate for the gutter-padding on the columns. Note that if you want your content to be flush with the side of the viewport, you will need to write another class to remove the gutter-padding on those column elements.

**Comment by dupski** [comment]
CodePen is gone again - experiencing the same issue. I will investigate the gutter sizing.....
