### ISSUE TITLE
Some child elements choose to fill the parent column instead of wrapping the child content

### ISSUE THREAD

**Issue by matt3224** [kristoferjoseph/flexboxgrid#61]
For instance if i have a row with 3 columns and in the first i have an a tag with an img inside the a will fill the column instead of being the height/width of the element

http://codepen.io/matt3224/pen/vEVwYW

Why is this?

**Comment by Aybee** [comment]
**Direct childs** of elements with display:flex; (normaly only the flex containers are set to display:flex;) automaticaly become flex items.

Because **.col** (a flex item) itself is set to **display:flex;** its children automaticaly also become flex items.

An a-tag, normaly an inline element, becomes a block element when it is a flex item.

You can set the columns to
```css
[class*="col"] {
  display: initial;
}
```
if you don't need children of flex items automaticaly also become flex items.

Parent - **display:flex;** (flex container)
-- Child (automaticaly a **flex item** with display **block**)
---- Grandchild (normal element behavior) 

Parent - **display:flex;** (flex container)
-- Child **display:flex;** (automaticaly a **flex item** with display **block** now also is a **flex container**)
---- Grandchild (now also automaticaly is a **flex item** with display **block**)

**Comment by matt3224** [comment]
Thanks for clearing that up. If I use the first option:

Parent - display:flex; (flex container)
-- Child (automaticaly a flex item with display block)
---- Grandchild (normal element behavior)

Will it in anyway affect the grid system, nesting for example?

**Comment by Aybee** [comment]
I don't think so. But I don't know exactly why .col is set to display:flex;. Take a look at the demo page where firstly every .col has a .box inside so you can avoid your a-tag problem. Secondly if you nest the grid in the demo every nested grid again has a .row.

**Comment by kristoferjoseph** [comment]
Yes what @Aybee said. Thanks for helping to clear that up!

**Comment by Aybee** [comment]
@kristoferjoseph 
But why have you set .col to display:flex;? I think .cols only should be flex items and no flex containers. Can't you do it without that? Or are there some reasons you can't remember?

If I try the demo page without
```css
  display: -webkit-box;
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;
  -webkit-box-orient: vertical;
  -webkit-box-direction: normal;
  -webkit-flex-direction: column;
  -ms-flex-direction: column;
  flex-direction: column;
```
on all .cols, then I can't find any difference. This all are properties which only belong to flex containers.

**Comment by kristoferjoseph** [comment]
@Aybee the columns had display flex in order to allow you to add layout classes to a column. This was to support vertical layouts when not using a row. I didn't end up fleshing this out so possibly this could be added to a modifier class that enables column only layouts later on.
