### ISSUE TITLE
Confused by the documentation vs. code

### ISSUE THREAD

**Issue by dandv** [kristoferjoseph/flexboxgrid#83]
I'm a new user and trying to make sense of how the code samples at http://flexboxgrid.com/ relate to the demos right above them. Without an introductory section, I'm not sure at times if I'm reading a guide on how to use Flexboxgrid, or how some of its features are implemented.

For example, at [Fluid](http://flexboxgrid.com/#fluid), the demo consists of a series of 7 `col-xs` pairs (except the first one) that add up to 12, but the code is

```css
.col-xs-6 {
  flex-basis: 50%;
}
```

(I expected to see the HTML code that makes up the grid above, since I got used to that doc convention in Bootstrap, MateriaizeCSS etc.)

The Auto Width example is clearer, but the demo code reads `<div class="box">`, while the actual code uses the `box-row` class.

The Nested Grids example uses a `box-container` class and a `box-first` one. Neither is documented.

What am I missing that's causing this documentation disconnect?

**Comment by kristoferjoseph** [comment]
You are thinking too much about it.
The box classes are just styling added so you can see the effects of the flexboxgrid on elements contained within. It does not make sense to document the box styles because they are only for a visual example.
This is documenting flexboxgrid classes not flexbox. There are plenty of places to read up on flexbox if you want that.
